apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-micro-service-three-deployment
spec:
  selector:
    matchLabels:
      micro-service-three-vertx:  v1
  replicas: 2
  template:
    metadata:
      labels:
        micro-service-three-vertx:  v1
    spec:
      containers:
        - name: micro-service-three-vertx
          image: 971734603674.dkr.ecr.us-east-1.amazonaws.com/cc/micro3:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1000m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: micro-service-three-vertx-hpa

  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vertx-micro-service-three-deployment
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
