apiVersion: v1
kind: Service
metadata:
  name: vertx-micro-service-three-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    micro-service-three-vertx:  v1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
