###
# vert.x docker example using a Java verticle packaged as a fatjar
# To build:
#  docker build -t sample/vertx-java-fat .
# To run:
#   docker run -t -i -p 8080:8080 sample/vertx-java-fat
###

FROM maven:3.8.3-jdk-8-slim

EXPOSE 80

COPY ./pom.xml /usr/local/
COPY ./src /usr/local/src

WORKDIR /usr/local/

# Use Bash as the container's entry point.
ENTRYPOINT ["/bin/bash", "-c", "export MYSQL_PWD=????? && export MYSQL_NAME=????? && export MYSQL_HOST=mysql-read.default.svc.cluster.local && mvn clean install && mvn package && mvn exec:java -Drun.jvmArguments=\"-Dfile.encoding=UTF-8\""]

