apiVersion: v1
kind: Service
metadata:
  name: micro-service-2-vertx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    micro-service-2-vertx:  v1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
