kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv4
spec:
  capacity:
    storage: 120Gi
  claimRef:
    namespace: default
    name: data-mysql-4
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0fbaa6fbb110dcbd2
    fsType: ext4
